In [46]:
import numpy as np
import pandas as pd

from sklearn import datasets

In [47]:
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split

In [48]:
iris = datasets.load_iris()

In [49]:
X_train, X_test, Y_train, Y_test = train_test_split(iris.data, iris.target)
X_train

array([[6.7, 3. , 5.2, 2.3],
       [6.7, 3. , 5. , 1.7],
       [5.8, 2.7, 3.9, 1.2],
       [5.6, 2.7, 4.2, 1.3],
       [5.9, 3.2, 4.8, 1.8],
       [5.4, 3.7, 1.5, 0.2],
       [6.3, 2.5, 5. , 1.9],
       [6.4, 2.8, 5.6, 2.1],
       [5.5, 4.2, 1.4, 0.2],
       [6.3, 2.8, 5.1, 1.5],
       [6.2, 2.9, 4.3, 1.3],
       [5.4, 3.9, 1.7, 0.4],
       [5.7, 2.6, 3.5, 1. ],
       [6.7, 3.1, 5.6, 2.4],
       [6.4, 2.8, 5.6, 2.2],
       [5.5, 2.5, 4. , 1.3],
       [7.2, 3. , 5.8, 1.6],
       [6.7, 3.3, 5.7, 2.5],
       [6. , 2.2, 4. , 1. ],
       [4.9, 2.5, 4.5, 1.7],
       [7.6, 3. , 6.6, 2.1],
       [5.4, 3.4, 1.7, 0.2],
       [7.4, 2.8, 6.1, 1.9],
       [5.6, 2.5, 3.9, 1.1],
       [4.8, 3. , 1.4, 0.1],
       [4.4, 3. , 1.3, 0.2],
       [6.3, 2.7, 4.9, 1.8],
       [6.5, 3. , 5.8, 2.2],
       [5.8, 2.7, 5.1, 1.9],
       [5.1, 3.3, 1.7, 0.5],
       [5.1, 2.5, 3. , 1.1],
       [5.8, 2.7, 4.1, 1. ],
       [7.2, 3.2, 6. , 1.8],
       [4.9, 2.4, 3.3, 1. ],
       [7.3, 2

In [50]:
Y_train

array([2, 1, 1, 1, 1, 0, 2, 2, 0, 2, 1, 0, 1, 2, 2, 1, 2, 2, 1, 2, 2, 0,
       2, 1, 0, 0, 2, 2, 2, 0, 1, 1, 2, 1, 2, 1, 0, 0, 2, 1, 2, 0, 2, 1,
       0, 1, 1, 2, 0, 0, 1, 1, 2, 2, 1, 0, 1, 0, 0, 0, 0, 2, 2, 1, 0, 1,
       0, 1, 0, 2, 1, 1, 2, 1, 0, 2, 1, 2, 1, 0, 1, 0, 2, 1, 2, 2, 2, 2,
       0, 0, 0, 0, 1, 1, 2, 2, 2, 0, 0, 1, 2, 0, 0, 2, 2, 0, 2, 2, 1, 1,
       2, 0])

In [51]:
clf = LogisticRegression(max_iter=1000)

In [52]:
clf.fit(X_train,Y_train)

LogisticRegression(max_iter=1000)

In [53]:
clf.score(X_train,Y_train)

0.9821428571428571

In [54]:
clf.predict(X_test)

array([1, 1, 0, 0, 0, 1, 2, 2, 2, 0, 0, 0, 1, 0, 1, 1, 2, 0, 0, 0, 0, 2,
       1, 1, 0, 2, 2, 0, 0, 1, 1, 0, 2, 1, 1, 1, 0, 2])

In [55]:
Y_test_pred = clf.predict(X_test)

In [56]:
Y_train_pred = clf.predict(X_train)

In [57]:
from sklearn.metrics import confusion_matrix

# confusion matrix for TEST values in dataset 
confusion_matrix(Y_test, Y_test_pred)

array([[16,  0,  0],
       [ 0, 13,  1],
       [ 0,  0,  8]])

In [58]:
# confusion matrix for TRAIN values in dataset
confusion_matrix(Y_train, Y_train_pred)

array([[34,  0,  0],
       [ 0, 34,  2],
       [ 0,  0, 42]])

In [59]:
# overall to use confusion matrix we simply use it from sklearn and give first parameter as TRUE VALUES and second parameter as PREDICTED VALUES

In [60]:
# to show PRECISION and RECALL of the output values of CONFUSION Matrix
from sklearn.metrics import classification_report

print(classification_report(Y_test, Y_test_pred))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00        16
           1       1.00      0.93      0.96        14
           2       0.89      1.00      0.94         8

    accuracy                           0.97        38
   macro avg       0.96      0.98      0.97        38
weighted avg       0.98      0.97      0.97        38

