In [1]:
import tensorflow as tf

In [3]:
# creating constant


a

<tf.Tensor: shape=(), dtype=int32, numpy=2>

In [4]:
b = tf.constant(10)
b

<tf.Tensor: shape=(), dtype=int32, numpy=10>

In [5]:
c = a+b
c

<tf.Tensor: shape=(), dtype=int32, numpy=12>

In [29]:
import tensorflow as tf
with tf.compat.v1.Session() as sess:
    a = tf.constant(2)
    b = tf.constant(10)
    c = a + b
    print(sess.run(c))

20


In [31]:
import tensorflow as tf
with tf.compat.v1.Session() as sess:
    a1 = tf.constant([[1,2]])
    a2 = tf.constant([[1],[2]])
    mul = tf.matmul(a1,a2)
    print(sess.run(mul))
    print(a1)

[[5]]
Tensor("Const_11:0", shape=(1, 2), dtype=int32)
