In [1]:
import numpy as np

In [16]:
# defining own sigmoid function

def sig(z):
    return 1/(1 + np.exp(-z))

In [21]:
def derivativeSigmoid(z):
    return sig(z)*(1 - sig(z))

In [83]:
X = np.array([[0,0], [0,1], [1,0], [1,1]])
Y = np.array([[0,0,0,1]]).T

In [105]:
weights = 2*np.random.random([2,1]) - 1
bias = 2*np.random.random(1) - 1

weights, bias

(array([[ 0.28848966],
        [-0.28972253]]),
 array([-0.89137928]))

In [106]:
# forward propogation 

output0 = X
output = sig(np.dot(output0, weights)) + bias

lr = 0.1

In [80]:
for iter in range(1000):
    first_term = output - Y
    input_for_last_layer = np.dot(output0, weights) + bias
    second_term = derivativeSigmoid(input_for_last_layer)
    first_two_term_in_der = first_term * second_term
    first_two_term_in_der.shape
        # backward propogation
    changes_in_weights = np.array([[0.0], [0.0]])
    for i in range(2):
        for j in range(4):
            changes_in_weights[i][0] += first_two_term_in_der[j][0]*output0[j][i]
    weights = weights - lr*changes_in_weights
    bias_changes = 0.0
    for j in range(4):
        bias_changes += first_two_term_in_der[j][0]*1
    bias = bias - lr*bias_changes
    output = sig(np.dot(X, weights)) + bias
print(output)

[[19.03353293]
 [19.53313629]
 [19.53346006]
 [19.5335329 ]]


In [107]:
# we can multiply this in another way

for iter in range(1000):
    first_term = output - Y
    input_for_last_layer = np.dot(output0, weights) + bias
    second_term = derivativeSigmoid(input_for_last_layer)
    first_two_term_in_der = first_term * second_term
    first_two_term_in_der.shape
        # backward propogation
    changes_in_weights = np.dot(output0.T, first_two_term_in_der)
    weights = weights - lr*changes_in_weights
    bias_changes = np.sum(first_two_term_in_der)
    bias = bias - lr*bias_changes
    output = sig(np.dot(X, weights)) + bias
print(output)


[[-0.15815549]
 [ 0.183635  ]
 [ 0.19943374]
 [ 0.31157921]]
