In [2]:
import numpy as np

X = np.array([[0,0], [0,1], [1,0], [1,1]])
Y = np.array([[0,1,1,1]]).T


In [3]:
X.shape, Y.shape

((4, 2), (4, 1))

In [4]:
# defining own sigmoid function

def sig(z):
    return 1/(1 + np.exp(-z))

In [11]:
# defining weights here 1 hidden layer

wh = 2*np.random.random((2,2)) - 1
bh = 2*np.random.random((1,2)) - 1
wo = 2*np.random.random((2,1))  - 1
bo = 2*np.random.random(1) - 1

wh, bh, wo, bo

(array([[ 0.59701885, -0.51011708],
        [ 0.36381771, -0.97474197]]),
 array([[-0.96819205,  0.11473961]]),
 array([[-0.22414442],
        [-0.34606637]]),
 array([-0.08712039]))

In [12]:
output0 = X
outputHidden = sig(np.dot(output0, wh)) + bh
output  = sig(np.dot(outputHidden, wo)) + bo
output

array([[0.38595616],
       [0.40044966],
       [0.38862557],
       [0.40069939]])