In [1]:
import numpy as np

X = np.array([[0,0], [0,1], [1,0], [1,1]])
Y = np.array([[0,1,1,1]]).T


In [2]:
X.shape, Y.shape

((4, 2), (4, 1))

In [3]:
# defining own sigmoid function

def sig(z):
    return 1/(1 + np.exp(-z))

In [5]:
# defining weights but here no hidden layer

weights = 2*np.random.random((2,1)) - 1
bias = 2*np.random.random(1) - 1

weights, bias

(array([[0.89373352],
        [0.49401366]]),
 array([0.33653966]))

In [9]:
# store the input in another variable

output0 = X
# we need to do dot product of output0 with weights to get the outputs

output = sig(np.dot(output0, weights)) + bias

output

array([[0.83653966],
       [0.95759115],
       [1.0461997 ],
       [1.13677201]])