In [101]:
import cv2
import numpy as np

In [102]:
img = np.zeros((500,500,3))

In [103]:
# drawing rectangle

# here pt1 - left corner point in form of tupple
# pt2 - right bottom corner point in form of tupple
# color - in form of tupple 
# thickness - (-1) for fill with the current color otherwise anything

cv2.rectangle(img, pt1 = (200, 200), pt2 = (300, 300), color = (0,255,0),thickness = 10)

array([[[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        ...,
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        ...,
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        ...,
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       ...,

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        ...,
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        ...,
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        ...,
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]]])

In [104]:
# circle 

cv2.circle(img, center=(200,200), radius = 50, color = (0,0,255), thickness = -1)

array([[[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        ...,
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        ...,
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        ...,
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       ...,

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        ...,
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        ...,
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        ...,
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]]])

In [105]:
# line

cv2.line(img, pt1 = (0,0), pt2 = (500,500), color = (225, 10,0), thickness = 10)

array([[[225.,  10.,   0.],
        [225.,  10.,   0.],
        [225.,  10.,   0.],
        ...,
        [  0.,   0.,   0.],
        [  0.,   0.,   0.],
        [  0.,   0.,   0.]],

       [[225.,  10.,   0.],
        [225.,  10.,   0.],
        [225.,  10.,   0.],
        ...,
        [  0.,   0.,   0.],
        [  0.,   0.,   0.],
        [  0.,   0.,   0.]],

       [[225.,  10.,   0.],
        [225.,  10.,   0.],
        [225.,  10.,   0.],
        ...,
        [  0.,   0.,   0.],
        [  0.,   0.,   0.],
        [  0.,   0.,   0.]],

       ...,

       [[  0.,   0.,   0.],
        [  0.,   0.,   0.],
        [  0.,   0.,   0.],
        ...,
        [225.,  10.,   0.],
        [225.,  10.,   0.],
        [225.,  10.,   0.]],

       [[  0.,   0.,   0.],
        [  0.,   0.,   0.],
        [  0.,   0.,   0.],
        ...,
        [225.,  10.,   0.],
        [225.,  10.,   0.],
        [225.,  10.,   0.]],

       [[  0.,   0.,   0.],
        [  0.,   0.,   0.],
        [  0.,  

In [106]:
# creating fonts

cv2.putText(img, text = "Hello Sanoj",fontFace = 7 , fontScale = 2, color = (0, 125, 125), thickness = 3, org = (50,50))

array([[[225.,  10.,   0.],
        [225.,  10.,   0.],
        [225.,  10.,   0.],
        ...,
        [  0.,   0.,   0.],
        [  0.,   0.,   0.],
        [  0.,   0.,   0.]],

       [[225.,  10.,   0.],
        [225.,  10.,   0.],
        [225.,  10.,   0.],
        ...,
        [  0.,   0.,   0.],
        [  0.,   0.,   0.],
        [  0.,   0.,   0.]],

       [[225.,  10.,   0.],
        [225.,  10.,   0.],
        [225.,  10.,   0.],
        ...,
        [  0.,   0.,   0.],
        [  0.,   0.,   0.],
        [  0.,   0.,   0.]],

       ...,

       [[  0.,   0.,   0.],
        [  0.,   0.,   0.],
        [  0.,   0.,   0.],
        ...,
        [225.,  10.,   0.],
        [225.,  10.,   0.],
        [225.,  10.,   0.]],

       [[  0.,   0.,   0.],
        [  0.,   0.,   0.],
        [  0.,   0.,   0.],
        ...,
        [225.,  10.,   0.],
        [225.,  10.,   0.],
        [225.,  10.,   0.]],

       [[  0.,   0.,   0.],
        [  0.,   0.,   0.],
        [  0.,  

In [107]:
cv2.imshow("window", img)

cv2.waitKey(0)

-1