In [2]:
import numpy as np

X = np.array([[1,2,3],
            [4,5,6],
            [1,2,3]])

In [4]:
# import preprocessing from sklearn

from sklearn import preprocessing

X_scaled = preprocessing.scale(X)
X_scaled

array([[-0.70710678, -0.70710678, -0.70710678],
       [ 1.41421356,  1.41421356,  1.41421356],
       [-0.70710678, -0.70710678, -0.70710678]])

In [5]:
X_scaled.mean()

0.0

In [ ]:
X_scaled.std()

In [12]:
# another way to scale features

scaler = preprocessing.StandardScaler()
scaler.fit(X)
X_scaled2 = scaler.transform(X)
X_scaled2

array([[-0.70710678, -0.70710678, -0.70710678],
       [ 1.41421356,  1.41421356,  1.41421356],
       [-0.70710678, -0.70710678, -0.70710678]])

In [13]:
X_test = [[1,2,3]]
X_test3 = scaler.transform(X_test)
X_test3

array([[-0.70710678, -0.70710678, -0.70710678]])